endpoint: https://acme-staging.api.letsencrypt.org/

storage:
   type: filesystem
   path: ./test/storage

challenge_responders:
  - route53: {}

account_key_passphrase: password
certificate_key_passphrase: secret

post_issueing_hooks:
  "test.example.com":
    - shell:
        command: touch /tmp/step001-${COMMON_NAME}
    - shell:
        command: touch /tmp/step002-${COMMON_NAME}
  "admin.example.com":
    - shell:
        command:  echo $COMMON_NAME > /tmp/step003-${COMMON_NAME}
  "allow.no.failing.example.com":
    - shell:
        command:  /bin/iwillfail
  "allow.failing.example.com":
    - shell:
        command:  /bin/iwillfail
        ignore_failure: true
