endpoint: https://acme-staging.api.letsencrypt.org/

storage:
   type: filesystem
   path: ./test/storage

challenge_responders:
  - route53: {}

account_key_passphrase: password
certificate_key_passphrase: secret

post_issueing_hooks:
  "test.example.com":
    - shell:
        command: touch /tmp/step001
    - shell:
        command: touch /tmp/step002
    - sendmail:
        recipient: sysadmin@example.com
        subject: Key for <%= @common_name %> is issued
  "admin.example.com":
    - shell:
        command: echo "upload to aws with timestamp in name"
    - shell:
        command: echo "update elb cert with new"
    - shell:
        command: echo "remove old cert"
