endpoint: https://acme-staging.api.letsencrypt.org/

storage:
   type: filesystem
   path: ./test/storage

challenge_responders:
  - route53: {}

account_key_passphrase: password
certificate_key_passphrase: secret

post_issueing_hooks:
  "test.example.com":
    - shell:
        command: touch /tmp/step001-<%= @common_name %>
    - shell:
        command: touch /tmp/step002-<%= @common_name %>
    - sendmail:
        recipient: sysadmin@example.com
        subject: Key for <%= @common_name %> is issued
  "admin.example.com":
    - shell:
        command:  touch /tmp/step002-<%= @common_name %>
  "allow.no.failing.example.com":
    - shell:
        command:  /bin/iwillfail
  "allow.failing.example.com":
    - shell:
        command:  /bin/iwillfail
        ignore_failure: hallo
